var Modernizr = {
    "flexbox": {},
    "flexboxlegacy": {},
    "canvas": {},
    "canvastext": {},
    "webgl": {},
    "webaudio": {},
    "touch": {},
    "geolocation": {},
    "postmessage": {},
    "websqldatabase": {},
    "indexeddb": {},
    "hashchange": {},
    "history": {},
    "draganddrop": {},
    "websockets": {},
    "rgba": {},
    "hsla": {},
    "multiplebgs": {},
    "backgroundsize": {},
    "borderimage": {},
    "borderradius": {},
    "boxshadow": {},
    "textshadow": {},
    "opacity": {},
    "cssanimations": {},
    "csscolumns": {},
    "cssgradients": {},
    "cssreflections": {},
    "csstransforms": {},
    "csstransforms3d": {},
    "csstransitions": {},
    "fontface": {},
    "generatedcontent": {},
    "video": {
        "ogg": {},
        "h264": {},
        "webm": {}
    },
    "audio": {
        "ogg": {},
        "mp3": {},
        "wav": {},
        "m4a": {}
    },
    "localstorage": {},
    "sessionstorage": {},
    "webworkers": {},
    "applicationcache": {},
    "svg": {},
    "inlinesvg": {},
    "smil": {},
    "svgclippaths": {},
    "input": {
        "autocomplete": {},
        "autofocus": {},
        "list": {},
        "placeholder": {},
        "max": {},
        "min": {},
        "multiple": {},
        "pattern": {},
        "required": {},
        "step": {}
    },
    "inputtypes": {
        "search": {},
        "tel": {},
        "url": {},
        "email": {},
        "datetime": {},
        "date": {},
        "month": {},
        "week": {},
        "time": {},
        "datetime-local": {},
        "number": {},
        "range": {},
        "color": {}
    },
    "addTest": function () {},
    "_version": {},
    "_prefixes": {
        "0": {},
        "1": {},
        "2": {},
        "3": {},
        "4": {},
        "5": {}
    },
    "_domPrefixes": {
        "0": {},
        "1": {},
        "2": {},
        "3": {}
    },
    "_cssomPrefixes": {
        "0": {},
        "1": {},
        "2": {},
        "3": {}
    },
    "mq": function () {},
    "hasEvent": function () {},
    "testProp": function () {},
    "testAllProps": function () {},
    "testStyles": function () {},
    "prefixed": function () {}
}